# The GroupName here is used to identify your company or business unit that
# created this webhook.
# For example, this may be "acme.mycompany.com".
# This name will need to be referenced in each Issuer's `webhook` stanza to
# inform cert-manager of where to send ChallengePayload resources in order to
# solve the DNS01 challenge.
# This group name should be **unique**, hence using your own company's domain
# here is recommended.
groupName: certmanager.webhook.alidns

certManager:
  namespace: cert-manager
  serviceAccountName: cert-manager

image:
  repository: registry.cn-shenzhen.aliyuncs.com/adboard/cert-manager-webhook-alidns
  tag: latest
  pullPolicy: Always
  privateRegistrySecretName: regsecret

service:
  type: ClusterIP
  port: 443

resources:
  requests:
    cpu: 50m
    memory: 50Mi
